[package]
name = "signed_distance_fields"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math_vector = { git = "https://github.com/ThomasByr/rust-math_vector" }
itertools-num = "0.1.3"
image = "0.24.4"
palette = "0.6.1"

